### ISSUE TITLE
Feature request: react role functionality

### ISSUE THREAD

**Issue by shawnduong** [sealldeveloper/ctf-team-tool#1]
Just a humble feature request incoming :)

A lot of CTF teams (and Discord servers) have react roles. These automatically assign someone a role when they react to a message. Sometimes, messages can have multiple possible react roles that people can choose to have.

It'd be pretty cool if this project had that too so that CTF teams could reduce the number of bots that help maintain ops.

What could be even cooler is if the bot automatically detected this based on the message contents, but maybe that's a stretch. Something like:
> REACT
> :computer: Developer
> :radio: Ham Radio
> :lock: Lockpicker

I'd be down to help with this if you think it has a place in your project.

**Comment by sealldeveloper** [comment]
Good idea, I'll see what I can do!

**Comment by sealldeveloper** [comment]
Added reaction roles! Did not add auto-detection as I see that as a bit odd for the bot to have unneeded message content capabilities.

Let me know if you have any more ideas :)
